version: '3.7'

services:
  api:
    container_name: 'dm-display-api'
    build:
      context: '.'
    ports:
      - "${EXPOSE_SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .env:/home/node/app/.env
