# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: npm ci
      - run: npm run build-server --if-present
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: dm-display-server
          path: |
            lib
            .dockerignore
            Dockerfile
            docker-compose.yml
            package.json
            package-lock.json
            .env.example
